name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write # to create release (changesets/action)
  issues: write # to post issue comments (changesets/action)
  pull-requests: write # to create pull request (changesets/action)
  id-token: write # to use OpenID Connect token for trusted publishing (changesets/action)

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch git tags
        run: git fetch --tags origin

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
